### ISSUE TITLE
Out of memory error handling strategy

### ISSUE THREAD

**Issue by y-guyon** [webmproject/CrabbyAvif#91]
I see that some heap allocations are not explicitly checked:

https://github.com/webmproject/CrabbyAvif/blob/87cd46deccc5e47c7bb7891918596035da10b4b0/src/internal_utils/mod.rs#L166

While others are:

https://github.com/webmproject/CrabbyAvif/blob/87cd46deccc5e47c7bb7891918596035da10b4b0/src/internal_utils/mod.rs#L242-L243

What are the heap allocation checking guidelines in CrabbyAvif? Should we rely on panics/aborts for that and never use `AvifError::OutOfMemory`? Can such panics be caught at the C API interface layer?

**Comment by vigneshvg** [comment]
> What are the heap allocation checking guidelines in CrabbyAvif? Should we rely on panics/aborts for that and never use AvifError::OutOfMemory? Can such panics be caught at the C API interface layer?

The goal is to catch as many allocation errors as possible without panic/abort and return `AvifError::OutOfMemory`. Some places where it's easy to check for allocation already does. The others we need to try and change them to check for allocation failures.
